### ISSUE TITLE
Examples out of date

### ISSUE THREAD

**Issue by rtgibbons** [nodejitsu/node-cloudfiles#16]
Looks like yall have done some major refactoring.

The examples and documentation provided by the README are inaccurate. Seems to have come about with v0.3.0

**Comment by Marak** [comment]
Which examples? Do the tests pass for you?

A pull request would be appreciated.

**Comment by rtgibbons** [comment]
On the readme.

``` js
    client.addFile('myContainer', 'remoteName.txt', 'path/to/local/file.txt', function (err, uploaded) {
        // File has been uploaded
    });
```

And I don't have anything yet b/c I can't get the new addFile to actually save anything. I started to read through the Test and I honestly don't remember why I stopped, I'll read through and try again.

**Comment by Marak** [comment]
Do the tests pass? Run the tests. The units tests are there to ensure that the library is in working order. The examples are only there for connivence. 

There is no reason all tests shouldn't all be passing ( since we use this library in production everyday )

Run Tests

All of the node-cloudservers tests are written in vows, and cover all of the use cases described above. You will need to add your Rackspace API username and API key to test/fixtures/test-config.json before running tests:

  {
    "auth": {
      "username": "your-username",
      "apiKey": "your-apikey"
    }
  }
Once you have valid Rackspace credentials you can run tests with vows:

  vows test/*-test.js --spec

**Comment by rtgibbons** [comment]
The test run, that wasn't the issue. I just couldn't get it to work, and the ReadMe documentation wasn't accurate with the new code. 

I'll update the read me for yall as I think I have it now.

**Comment by rtgibbons** [comment]
created the pull for the .addFiles not sure if others have changed (the createContainer hasn't) This is now in issue 17
